[package]
name = "salmon_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30"
softbuffer = "0.4"
anyhow = "1.0"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
